name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@v1
        with:
            host: 3.87.155.238
            username: ubuntu
            key: ${{ secrets.KEY }}
            port: 22
            script: |
              mkdir -p /home/ubuntu/app
              cd /home/ubuntu/app
              rm -rf * # Clear old files
              git clone https://github.com/naveenreddy007/CICD-gitworkflow.git .
              /home/ubuntu/.nvm/versions/node/v22.14.0/bin/npm install
              /home/ubuntu/.nvm/versions/node/v22.14.0/bin/pm2 restart app || /home/ubuntu/.nvm/versions/node/v22.14.0/bin/pm2 start index.js --name app
