name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@v1
        with:
            host: 3.87.155.238
            username: ubuntu
            key: ${{ secrets.KEY }}
            port: 22
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm use 22

          mkdir -p /home/ubuntu/app
          cd /home/ubuntu/app
          rm -rf * # Clear old files

          # Ensure git clone works correctly
          if [ ! -d ".git" ]; then
            git clone https://github.com/naveenreddy007/CICD-gitworkflow.git .
          else
            git pull origin main  # If already cloned, update the repo
          fi

          npm install

          # Start or restart PM2 with --update-env
          if pm2 list | grep -q "app"; then
            pm2 restart app --update-env
          else
            pm2 start index.js --name app
          fi
